---
services:
  nginx:
    image: "nginx:latest"
    restart: "always"
    ports:
      - "80:80"
      - "443:443"
      # Uncomment for local development
      # - "8080:80"
    volumes:
      - ./conf:/etc/nginx
      - ./letsencrypt_prd:/etc/letsencrypt
    networks:
      - proxy
networks:
  proxy:
    name: "proxy"
