---
services:
  vaultwarden:
    container_name: "vaultwarden"
    image: vaultwarden/server:latest
    restart: unless-stopped
    ports:
      - "3333:80"
    volumes:
      - ./data:/data
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    driver: bridge
    external: true