---
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    volumes:
      - ./podtainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
volumes:
  portainer_data:
  
networks:
  proxy:
    name: proxy
    driver: bridge
    external: true
