---
networks:
  proxy:
    name: proxy
    driver: bridge
services:
  nginxproxymanager:
    image: docker.io/jc21/nginx-proxy-manager:2.11.3
    ports:
      - 80:80
      - 81:81
      - 443:443
    environment:
      - DB_MYSQL_HOST=nginxproxymanager-db
      - DB_MYSQL_PORT=3306
      - DB_MYSQL_USER=npm
      - DB_MYSQL_PASSWORD=npm
      - DB_MYSQL_NAME=npm
    volumes:
      - ./nginxproxymanager-data:/data
      - ./nginxproxymanager-ssl:/etc/letsencrypt
    restart: unless-stopped
    depends_on:
      nginxproxymanager-db:
        condition: service_healthy
        restart: true
  nginxproxymanager-db:
    image: docker.io/jc21/mariadb-aria:10.11.5
    environment:
      - MYSQL_ROOT_PASSWORD=npm
      - MYSQL_DATABASE=npm
      - MYSQL_USER=npm
      - MYSQL_PASSWORD=npm
    volumes:
      - ./nginxproxymanager-db:/var/lib/mysql
