---
services:
  traefik:
    image: docker.io/library/traefik:2.11.1
    container_name: traefik
    ports:
      - 80:80
      - 443:443
        # Enable for dashboard. Disable for production or enhance security
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/conf/:/etc/traefik/conf/
      - ./config/certs/:/etc/traefik/certs/
    environment:
      - CF_DNS_API_TOKEN=-EVftOVd0UB2IdE4SPCLKNGmI9P0N1YtiCLHaIQK
    networks:
      - proxy
    restart: unless-stopped

  nginxError:
    image: nginx:latest
    container_name: nginxError
    restart: unless-stopped
    volumes:
      - ./error-pages/html/:/usr/share/nginx/error-pages
      - ./error-pages/nginx-error-pages.conf:/etc/nginx/conf.d/default.conf
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.error-router.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.error-router.priority=1"
      - "traefik.http.routers.error-router.entrypoints=web"
      - "traefik.http.routers.error-router.middlewares=error-pages-middleware"
      - "traefik.http.middlewares.error-pages-middleware.errors.status=400-599"
      - "traefik.http.middlewares.error-pages-middleware.errors.service=error-pages-service"
      - "traefik.http.middlewares.error-pages-middleware.errors.query=/{status}.html"
      - "traefik.http.services.error-pages-service.loadbalancer.server.port=80"
networks:
  proxy:
    name: proxy
    driver: bridge
