---
services:
  # whoami:
  #   image: containous/whoami
  #   networks:
  #     - proxy
  #   labels:
  #     - "traefik.enable=true"
  #     # - "traefik.http.services.whoami.loadbalancer.server.port=80"
  #     - "traefik.http.routers.whoami.rule=Host(`whoami.zadinfra.com`)"
  #     # - "traefik.http.routers.whoami.service=whoami"
  #     - "traefik.http.routers.whoami.entrypoints=web,websecure"
  #     - "traefik.http.routers.whoami.middlewares=test-redirectscheme"
  #     - "traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https"
  #     - "traefik.http.routers.whoami.tls=true"
  #     - "traefik.http.routers.whoami.tls.certresolver=production"
  #     - "traefik.http.routers.whoami.tls.domains[0].main=zadinfra.com"
  #     - "traefik.http.routers.whoami.tls.domains[0].sans=*.zadinfra.com"
  web1:
    image: nginx:latest
    container_name: web_1
    # volumes:
    #   - ./web1/:/usr/share/nginx/html/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web1_http.rule=Host(`web1.zadinfra.com`)"
      - "traefik.http.routers.web1_http.entrypoints=web"

      - "traefik.http.routers.web1_https.rule=Host(`web1.zadinfra.com`)"
      - "traefik.http.routers.web1_https.entrypoints=websecure"
      - "traefik.http.routers.web1_https.tls=true"
      - "traefik.http.routers.web1_https.tls.certresolver=production"
      - "traefik.http.routers.web1_https.tls.domains[0].main=zadinfra.com"
      - "traefik.http.routers.web1_https.tls.domains[0].sans=*.zadinfra.com"

    networks:
      - proxy

  web2:
    image: nginx:latest
    container_name: web_2
    # volumes:
    #   - ./web2/:/usr/share/nginx/html/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web2_http.rule=Host(`web2.zadinfra.com`)"
      - "traefik.http.routers.web2_http.entrypoints=web"
      - "traefik.http.routers.web2_https.rule=Host(`web2.zadinfra.com`)"
      - "traefik.http.routers.web2_https.entrypoints=websecure"
      - "traefik.http.routers.web2_https.tls=true"
      - "traefik.http.routers.web2_https.tls.certresolver=production"
      - "traefik.http.routers.web2_https.tls.domains[0].main=zadinfra.com"
      - "traefik.http.routers.web2_https.tls.domains[0].sans=*.zadinfra.com"

    networks:
      - proxy

networks:
  proxy:
    name: proxy
    external: true
